# Generated by Django 3.2.5 on 2021-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('total_ct_chng_q4_q1', models.FloatField(blank=True, db_column='Total_Ct_Chng_Q4_Q1', null=True)),
                ('total_trans_amt', models.IntegerField(blank=True, db_column='Total_Trans_Amt', null=True)),
                ('total_revolving_bal', models.IntegerField(blank=True, db_column='Total_Revolving_Bal', null=True)),
                ('total_relationship_count', models.IntegerField(blank=True, db_column='Total_Relationship_Count', null=True)),
                ('total_amt_chng_q4_q1', models.FloatField(blank=True, db_column='Total_Amt_Chng_Q4_Q1', null=True)),
                ('total_trans_ct', models.IntegerField(blank=True, db_column='Total_Trans_Ct', null=True)),
                ('contacts_count_12_mon', models.IntegerField(blank=True, db_column='Contacts_Count_12_mon', null=True)),
                ('attrition_flag', models.TextField(blank=True, db_column='Attrition_Flag', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
    ]
